name: 'OWASP dependency check'

on: [ push, workflow_dispatch ]

jobs:
  build:
    name: "Using Java ${{ matrix.java }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: false

      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: 'OWASP Dependency Check'
        run: mvn clean package org.owasp:dependency-check-maven:aggregate -Dspotless.apply.skip=true -Dall -DskipTests=true -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -T2.2C -Pdependencycheck

      - name: 'Upload scan results to GitHub Code Scanning'
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: target/dependency-check-report.sarif
